In [1]:
import torch
import torch.nn as nn

In [3]:
loss_fct_hallucination = nn.CrossEntropyLoss(ignore_index=-100)
loss_fct_token = nn.CrossEntropyLoss(ignore_index=-100)

In [49]:
token_pred = torch.tensor([[10, 9, 9], [1, 22, 3], [1, 1, 1.0]])
token_labels = torch.tensor([0, -100, -100])
token_loss = loss_fct_token(token_pred, token_labels)
print(torch.nn.Softmax(dim=-1)(token_pred))
print(token_loss)

tensor([[5.7612e-01, 2.1194e-01, 2.1194e-01],
        [7.5826e-10, 1.0000e+00, 5.6028e-09],
        [3.3333e-01, 3.3333e-01, 3.3333e-01]])
tensor(0.5514)


In [47]:
hallucination_pred = torch.tensor([[11.0, 2, 3], [1, 22, 3], [1, 1, 1]])
hallucination_labels = torch.tensor([0, 1, 2])
hallucination_loss = loss_fct_hallucination(hallucination_pred, hallucination_labels)
print(hallucination_loss)

tensor(0.3664)


In [48]:
total_loss = token_loss + hallucination_loss
print(total_loss)

tensor(81.0595)


In [5]:
mask_no_hallucination = torch.tensor([True, False, False])
mask_is_deletion_token = torch.tensor([False, False, True])

In [6]:
combined_mask = (mask_no_hallucination | mask_is_deletion_token).unsqueeze(-1)

In [7]:
combined_mask

tensor([[ True],
        [False],
        [ True]])

In [10]:
logits = torch.tensor([2.0, 1, 0.5, 4, 8, 2, 3, 6, 2, 1, 3.1, 2, 3, 1, 1, 4, 5, 3, 2, 1])
probs = torch.nn.Softmax(dim=-1)(logits)
print(probs)

tensor([1.9565e-03, 7.1976e-04, 4.3656e-04, 1.4457e-02, 7.8932e-01, 1.9565e-03,
        5.3184e-03, 1.0682e-01, 1.9565e-03, 7.1976e-04, 5.8777e-03, 1.9565e-03,
        5.3184e-03, 7.1976e-04, 7.1976e-04, 1.4457e-02, 3.9298e-02, 5.3184e-03,
        1.9565e-03, 7.1976e-04])


In [11]:
logits = torch.tensor([2.0, 1, 0.5, 4, 8, 2, 3, 6, 2, 1, 3.1, 2, 3, 1, 1, 4, 5, 3, 2, 1, 2, 2])
probs = torch.nn.Softmax(dim=-1)(logits)
print(probs)

tensor([1.9489e-03, 7.1696e-04, 4.3486e-04, 1.4400e-02, 7.8624e-01, 1.9489e-03,
        5.2976e-03, 1.0641e-01, 1.9489e-03, 7.1696e-04, 5.8548e-03, 1.9489e-03,
        5.2976e-03, 7.1696e-04, 7.1696e-04, 1.4400e-02, 3.9145e-02, 5.2976e-03,
        1.9489e-03, 7.1696e-04, 1.9489e-03, 1.9489e-03])
